### ISSUE TITLE
Genome and Realm can be used together ?

### ISSUE THREAD

**Issue by arden** [LoganWright/Genome#10]
Genome and Realm can be used together ?

**Comment by LoganWright** [comment]
Hi @arden 

I haven't explicitly tested with Realm, but there shouldn't be anything preventing you from using realm:

```
class SomeModel : Object, BasicMappable {
    required init() {}

    func sequence(map: Map) throws {
        // ... etc.
    }
}

```

I'm happy to answer any questions you have along the way to get you started :)

Best,

Logan
