### ISSUE TITLE
Int64 unexpected value mapping error

### ISSUE THREAD

**Issue by max-potapov** [LoganWright/Genome#25]
Could you describe how to use Genome with Int64 type? I'm getting error while trying to map:

> "UnexpectedValue("Found: 42 ofType: __NSCFNumber Expected: Int64 KeyPath: id TargetType: Int64")\n"

Here is sample:
```swift
let string = "{ \"id\": 42 }"
let data = string.dataUsingEncoding(NSUTF8StringEncoding)
let json = try? NSJSONSerialization.JSONObjectWithData(data!, options: .AllowFragments)

struct Sample: BasicMappable {
    private(set) var id: Int64 = 0
    mutating func sequence(map: Map) throws {
        try id <~> map["id"]
    }
}

do {
    let sample = try Sample.mappedInstance(json as! JSON)
    print(sample.id)
} catch {
    print(error)
}
```

**Comment by LoganWright** [comment]
Hi @max-potapov 

Thanks for checking out the library!  I'm going to see what I can do on my end to prevent errors like this from happening but for now, here's what's going on.

In JSON, we're unsure the specific type of a number so it bridges to _NSCFNumber which can be automatically converted to types like: `Int`, `Double`, and `Float`.

Unfortunately, it looks like its choking on `Int64`. (and I imagine other types, such as `UInt8`, etc...

There's two fixes temporarily:

1. Use `Int`

I'd probably do this.  The highest supported architecture at the moment is 64 bit, so you should be fine using just `Int` unless you really want to limit to 64 bit number.

2. Transform

```
try id <~> map["id"]
.transformFromJson { (input: Int) -> Int64 in return Int64(input) }
```

Let me know if I can help with anything else!

- Logan

**Comment by max-potapov** [comment]
Thanks. I'll try second option due to Core Data roots (Int16/32/64/NSNumber).

**Comment by LoganWright** [comment]
@max-potapov Using the new type system, all Integer types should be supported.  Let me know if you run into problems upgrading, there are some other syntax changes as well.

**Comment by max-potapov** [comment]
@LoganWright Just checked with latest release: everything works fine. Thank you!
