### ISSUE TITLE
transformToJson to NSNull

### ISSUE THREAD

**Issue by jhihguan** [LoganWright/Genome#36]
```Swift
// Genome 1.0
try self.note ~> map["note"]
  .transformToJson {
    $0 ?? NSNull()
  }
```
```Swift
// Genome 2.0
try self.note ~> map["note"]
  .transformToJson { (value: String?) -> String in
    if let text = value {
      return text
    }
    return "\(NSNull())"
  }
```

In Genome 1.0, I can `transformToJson` from nil to NSNull by first code block
but In Genome 2.0, I have to change the transform code to second block which does not actually return NSNull as I want but a String

does there have some way to do the function like before?

**Comment by LoganWright** [comment]
Hi @jhihguan Can I ask what type `note` is?

If it's type `String` and you were assigning `NSNull`, then it was likely some weird foundation thing that shouldn't have happened in the first place.  Is there a reason you need this value to account for `NSNull` that would prevent it from being a simple optional string: `String?`

Happy to help figure this out with you so we can get you back on track w/ version 2.0 :)

**Comment by LoganWright** [comment]
@jhihguan I was wrong earlier when I mentioned that.  Since you're transforming to Json, you will need to use an enclosed Json type:

```Swift
try self.note ~> map["note"]
  .transformToJson { (value: String?) -> Json in
    if let text = value {
      return .from(text)
    }
    return .NullValue
  }
```

**Comment by jhihguan** [comment]
@LoganWright Cool!! Thanks for helping me this, didn't know that I can return a Json type when transformToJson
