### ISSUE TITLE
jsonRepresentation can not cast to AnyObject

### ISSUE THREAD

**Issue by jhihguan** [LoganWright/Genome#39]
In v1.0.8
I can do this directly(obj is a class object confirm to BasicMappable)
```Swift
  var basic = [String: AnyObject]()
  basic["obj"] = obj.jsonRepresentation()
```

But in v2, it won't work and I can't even cast to AnyObject
```Swift
if let dict = try obj.jsonRepresentation() as? AnyObject {
  basic["obj"] = dict
}
```

I'm using Alamofire to do a POST which take Dictionary<String, AnyObject> as parameter and assemble to string automatically, does there a way to do things like before?

**Comment by jhihguan** [comment]
Currently, I'm doing a tricky way by transform Json -> description -> data -> object
```Swift
let text = try obj.jsonRepresentation().description
let dict = try NSJSONSerialization.JSONObjectWithData(text.dataUsingEncoding(NSUTF8StringEncoding)!, options: .AllowFragments)
basic["obj"] = dict
```

**Comment by douglasd3** [comment]
Same problem here.

**Comment by LoganWright** [comment]
@jhihguan @douglasd3 

This is an issue related to moving away from Foundations implicit casting.  If you're in a Foundation environment, you'll need to tag onto the end:

```
try obj.jsonRepresentation().anyValue
```

It may be worth wrapping it:

```
extension MappableObject {
    func foundationJsonRepresentation() throws -> AnyObject {
        return try jsonRepresentation().anyValue
    }
}
```

Let me know if this solves your problem guys and any input into how you'd prefer to interact with the api.

**Comment by LoganWright** [comment]
I also wanted to mention, that if you're looking for type `[String : AnyObject]`, you can do:

```
try obj.jsonRepresentation().foundationDictionary
```

**Comment by jhihguan** [comment]
@LoganWright 
There's an issue when accessing `anyValue`
I created a PullRequest in JsonSerializer

**Comment by LoganWright** [comment]
@jhihguan I went ahead and grabbed that right now, thank you for the fix!

If you update your pod, you should be good to go.  Make sure it bumps you to `1.0.2` of the JsonSerializer

**Comment by jhihguan** [comment]
Thanks @LoganWright 

Here's my opinion about this

I think it would be great to have this info (anyValue, foundationDictionary) show on README?
Cause for me, the json means Dictionary class. It will help developer figure out how they can get the true dictionary object.

Here's my lazy thought
Besides, it good for me if this is built in (also the `foundationDictionary`), so I don't have to import another library (sorry for lazy...)
```
extension MappableObject {
    func foundationJsonRepresentation() throws -> AnyObject {
        return try jsonRepresentation().anyValue
    }
}
```

I'm fine with the usage of `jsonRepresentation().anyValue`, just throw out my thought

Thanks again :)

**Comment by LoganWright** [comment]
@jhihguan 

I think that would be a great addition while people are getting used to Json as an enum.  I think I'd go one step further and say it should return `[String : AnyObject]`.

We could also write an implementation of this on collectionType that returns: `[AnyObject]`.

I think that would cover a good amount of use cases.

**Comment by LoganWright** [comment]
In 3.0, 

- foundationJSON
- foundationDictionary
- foundationArray
