### ISSUE TITLE
'String' is not convertible to 'KeyType'

### ISSUE THREAD

**Issue by innoreq** [LoganWright/Genome#63]
Hello,

first of all: great library. I just moved from another lib to Genome, and I find it much more transparent and efficient.

My problem: I want to save a `UIImage`, using this code in the `sequence` function:

```
		try image <~> map["image"]
			.transformFromJson {
				let stringData = $0
				let image = UIImage.fromBase64(stringData)
				return UIImage(data: imageData)
		}
			.transformToJson {
				let image: UIImage = $0
				let stringData = image.toBase64()
				return stringData
		}
```

However, this does not compile, as the error "'String' is not convertible to 'KeyType'" is thrown. What goes wrong, and how to fix it?

Thank a lot in advance!

- Hardy

**Comment by giacgbj** [comment]
What about this different approach?

public struct SomeStruct : MappableObject {
     public var image: UIImage!

     public init(map: Map) throws {
        try image = map.extract("image", transformer: { UIImage(data: NSData(base64EncodedString: $0, options: NSDataBase64DecodingOptions())!) })
    }

    public mutating func sequence(map: Map) throws {
        try image ~> map["image"].transformToJson{ UIImagePNGRepresentation($0)!.base64EncodedStringWithOptions([]) }

    }
}

**Comment by innoreq** [comment]
Good hint, works perfectly. I used this also for NSURL and other special stuff.
