### ISSUE TITLE
Swift 3 / Xcode 8 / Carthage: usable version available soon?

### ISSUE THREAD

**Issue by t-unit** [LoganWright/Genome#65]
Are there plans to have a working version of this very nice project soon that can be used with Swift 3 and be checkout out via Carthage?

I had a look at #58 but current state doesn't even contain a Xcode project. The Swift 3 branch over at [PureJsonSerializer](https://github.com/gfx/Swift-PureJsonSerializer/pull/17) also seems very outdated.

Would be cool to have and working Swift 3 version soon. It's the one thing holding me back from upgrading to Xcode 8.

**Comment by high5code** [comment]
+1

**Comment by LoganWright** [comment]
Hey, I'll be hopping on this more sometime next week. I don't know how Carthage works well enough, does it require an xcodeproj. 3.0 has been building to swift official package manager, but there's less iOS support than I had planned on. 

I may need to add project back if that ends up being the case. 

Thanks!

**Comment by t-unit** [comment]
Great to know you are on it!

 Yes, Carthage needs a Xcode project. In particular a framework target with a shared scheme.

If you need some help let me know. I'm happy to contribute some bits and pieces.

**Comment by LoganWright** [comment]
@t-unit I finished the final touches intended, and I've reached a point I feel comfortable calling 3.0. As I mentioned earlier, this is largely structured around SwiftPM, and there are going to be some minor modifications required to make it Cocoapods and Carthage ready.

This work is started here: #68 

I have no idea how to begin working on Carthage even, so any help getting it up to spec would be great. There are no longer any dependency requirements necessary, so should be easier to configure in theory.

**Comment by t-unit** [comment]
Basically it is already working. I'm currently testing if there are still some problems. 

I did some some small adjustments – #69. Not sure if you actually want to merge them since the whole Xcode project got recreated.

**Comment by LoganWright** [comment]
@t-unit That should be ok short term. For Carthage, is the xcproj required to be top level directory?

If no, perhaps we can nest it in a folder and maintain it, then we can leave other project gitignored and generate for dev.

Waiting on Travis, then I'll merge PR and tag 3.0.1

**Comment by LoganWright** [comment]
Merged and tagged @t-unit https://github.com/LoganWright/Genome/releases/tag/3.0.1

Thank you for your help 🙌

**Comment by t-unit** [comment]
@LoganWright thanks for merging.

Having the Xcode project file in a subfolder is absolutely no problem ([reference](https://github.com/Carthage/Carthage/issues/1047)). So feel free to move it around.
